### ISSUE TITLE
Extreme CPU usage

### ISSUE THREAD

**Issue by 010011x** [OpenBB-finance/pywry#77]
This is continuation of this issue

https://github.com/OpenBB-finance/OpenBBTerminal/issues/5104

Just running this example
```
import asyncio
import sys

from pywry import PyWry


async def main_loop():
    while True:
        await asyncio.sleep(1)


if __name__ == "__main__":
    try:
        handler = PyWry()
        handler.send_html("<h1 style='color: red;'>Welcome to PyWry!</h1>")
        handler.start()

        # PyWry creates a new thread for the backend,
        # so we need to run the main loop in the main thread.
        # otherwise, the program will exit immediately.
        handler.loop.run_until_complete(main_loop())
    except KeyboardInterrupt:
        print("Keyboard interrupt detected. Exiting...")
        sys.exit(0)
```

Gives 100 CPU usage. Why is that ? This consumes more cpu than anything else in openbb.

Is it busy waiting ?
Is it missing `asyncio.sleep` somewhere?

**Comment by andrewkenreich** [comment]
hey @010011x we are able to replicate this - looking into it!

**Comment by tehcoderer** [comment]
Hey @010011x ! Thank you for bringing this to our attention.

I spent all day today pulling my hair looking for the cause of this issue 😅, but the good news is I was able to pin point the cause of the CPU buffet fest lol.

![image](https://github.com/OpenBB-finance/pywry/assets/61340027/70a03f60-92dc-4ff8-8caa-fa4f2da21583)

🎊🚀 Running new build `v0.5.12` that should be installable in the next 15mins!

Thanks again for posting this Issue!

**Comment by 010011x** [comment]
> Hey @010011x ! Thank you for bringing this to our attention.
> 
> I spent all day today pulling my hair looking for the cause of this issue sweat_smile, but the good news is I was able to pin point the cause of the CPU buffet fest lol.
> 
> ![image](https://user-images.githubusercontent.com/61340027/244532128-70a03f60-92dc-4ff8-8caa-fa4f2da21583.png)
> 
> confetti_ballrocket Running new build `v0.5.12` that should be installable in the next 15mins!
> 
> Thanks again for posting this Issue!

great job !!! :rocket: that was really fast! thanks a lot!
