### ISSUE TITLE
Build failure on Linux with wry 0.31.0

### ISSUE THREAD

**Issue by rannokki** [OpenBB-finance/pywry#87]
Tested on Linux with rustc 1.72.0 and 1.64.0 and python 3.9 and 3.10 in a clean conda environment, installing pywry through pip.

Build fails because method [EventLoop::with_user_event](https://docs.rs/wry/0.30.0/wry/application/event_loop/struct.EventLoop.html#method.with_user_event) is used and wry 0.31.0 is specified in Cargo.toml, even though this method was dropped in [0.31.0](https://docs.rs/wry/0.31.0/wry/application/event_loop/struct.EventLoop.html).

```
error[E0599]: no function or associated item named `with_user_event` found for struct `EventLoop<_>` in the current scope
         --> src/headless.rs:160:52
          |
      160 |     let event_loop: EventLoop<UserEvent> = EventLoop::with_user_event();
          |                                                       ^^^^^^^^^^^^^^^ function or associated item not found in `EventLoop<_>`


      error[E0599]: no function or associated item named `with_user_event` found for struct `EventLoop<_>` in the current scope
         --> src/window.rs:223:52
          |
      223 |     let event_loop: EventLoop<UserEvent> = EventLoop::with_user_event();
          |                                                       ^^^^^^^^^^^^^^^ function or associated item not found in `EventLoop<_>`
```

That being said, `with_user_event` still exists in class `EventLoopBuilder`, and the latter is used by pywry in `headless.rs` and `window.rs` on Windows and Mac platforms. Should we use it on all platforms now?

**Comment by rannokki** [comment]
Just noticed the `Cargo-linux.toml` file with wry 0.23 in it. Sorry I missed that.
But running `pip install pywry` on Linux still uses `Cargo.toml` with wry 0.31.
Is that to be expected?

**Comment by tehcoderer** [comment]
Thanks for letting me know, this sould be fixed now! 

can you confirm? `pip install pywry==0.6.1`

I tested on the following 

# AlmaLinux 8
![image](https://github.com/OpenBB-finance/pywry/assets/61340027/6c71c156-a3e1-4831-916f-7ca3f28dafd5)

# Ubuntu 20.04
![image](https://github.com/OpenBB-finance/pywry/assets/61340027/d7b3c24c-7eab-4541-9352-09d1cfacd5c6)

**Comment by rannokki** [comment]
Thanks!

Looks like it's working now.
I did a checkout of branch v0.6.1 and `maturin build` succeeded.
(I can't have `pip install pywry==0.6.1 --no-cache-dir` work, but this is because of a dependency issue with javascriptcoregtk on my system. But since checkouting the repo and building from within it worked, I think we can consider the issue to be fixed.)

**Comment by tehcoderer** [comment]
Awesome 🚀, Glad to hear the changes fixed the issue for you 😊

Thanks again for bring this to our attention!
