### ISSUE TITLE
Security Address

### ISSUE THREAD

**Issue by SCH227** [OpenBB-finance/pywry#90]
Hello!

I may have found a security issue in latest version of pywry. Following responsible disclosure, is there an email or other private channel where I could share the details?
Thank you

**Comment by andrewkenreich** [comment]
yes please - juan.alfonso@openbb.finance

**Comment by tehcoderer** [comment]
fixed thank you

**Comment by SCH227** [comment]
Do you have an ETA for a patched release on PyPI?

**Comment by tehcoderer** [comment]
pushed!
